
#include "routes.h"
#include <crow.h>
#include <string>

namespace api {
void start_api()
{
    crow::SimpleApp app;

    CROW_ROUTE(app, "/mock")
    ([](const crow::request& req) {
        crow::json::wvalue x(crow::json::wvalue::list{ { { "id", 1 },
                                       { "name", "Jaymie Rogahn" },
                                       { "rankingScore", 0.67 },
                                       { "distance", 42.72 },
                                       { "city", "Lucaschester" },
                                       { "street", "Zemlak Row" },
                                       { "house_number", "101" } },
                                     { { "id", 2 },
                                       { "name", "Berniece Buckridge" },
                                       { "rankingScore", 0.77 },
                                       { "distance", 78.65 },
                                       { "city", "West Annelle" },
                                       { "street", "Borer Terrace" },
                                       { "house_number", "226" } },
                                     { { "id", 3 },
                                       { "name", "Hazel Monahan" },
                                       { "rankingScore", 0.89 },
                                       { "distance", 34.96 },
                                       { "city", "Lakeshatown" },
                                       { "street", "Justa Junction" },
                                       { "house_number", "1" } },
                                     { { "id", 4 },
                                       { "name", "Harold White" },
                                       { "rankingScore", 0.53 },
                                       { "distance", 100.23 },
                                       { "city", "North Verna" },
                                       { "street", "Osvaldo Avenue" },
                                       { "house_number", "10" } },
                                     { { "id", 5 },
                                       { "name", "Lyda Bergnaum" },
                                       { "rankingScore", 0.60 },
                                       { "distance", 72.44 },
                                       { "city", "Mitchelltown" },
                                       { "street", "Clair Light" },
                                       { "house_number", "17" } },
                                     { { "id", 6 },
                                       { "name", "Roxann Kohler" },
                                       { "rankingScore", 0.81 },
                                       { "distance", 76.45 },
                                       { "city", "North Rhett" },
                                       { "street", "Heaney Lodge" },
                                       { "house_number", "7" } },
                                     { { "id", 7 },
                                       { "name", "Isidro McClure" },
                                       { "rankingScore", 0.36 },
                                       { "distance", 56.12 },
                                       { "city", "New Shonnaland" },
                                       { "street", "Gottlieb Grove" },
                                       { "house_number", "44" } },
                                     { { "id", 8 },
                                       { "name", "Alva Stiedemann" },
                                       { "rankingScore", 0.20 },
                                       { "distance", 99.63 },
                                       { "city", "Boscofort" },
                                       { "street", "Reinger Ford" },
                                       { "house_number", "91" } },
                                     { { "id", 9 },
                                       { "name", "Robert Conroy" },
                                       { "rankingScore", 0.51 },
                                       { "distance", 80.06 },
                                       { "city", "Lake Myriamtown" },
                                       { "street", "Beier Bypass" },
                                       { "house_number", "191" } },
                                     { { "id", 10 },
                                       { "name", "Jada Heathcote" },
                                       { "rankingScore", 0.54 },
                                       { "distance", 14.70 },
                                       { "city", "Shawnaborough" },
                                       { "street", "Ying Stravenue" },
                                       { "house_number", "5" } },
                                     { { "id", 11 },
                                       { "name", "Angie Bernier" },
                                       { "rankingScore", 0.10 },
                                       { "distance", 116.22 },
                                       { "city", "Consuelofort" },
                                       { "street", "Merrill Highway" },
                                       { "house_number", "56" } },
                                     { { "id", 12 },
                                       { "name", "Murray Jerde" },
                                       { "rankingScore", 0.09 },
                                       { "distance", 49.77 },
                                       { "city", "West Alvaland" },
                                       { "street", "Watsica Plains" },
                                       { "house_number", "6" } },
                                     { { "id", 13 },
                                       { "name", "Berenice Deckow" },
                                       { "rankingScore", 0.14 },
                                       { "distance", 72.00 },
                                       { "city", "Beermouth" },
                                       { "street", "Chadwick Brook" },
                                       { "house_number", "54" } },
                                     { { "id", 14 },
                                       { "name", "Rafael Stanton" },
                                       { "rankingScore", 0.88 },
                                       { "distance", 61.35 },
                                       { "city", "West Eulaliabury" },
                                       { "street", "Xiomara Row" },
                                       { "house_number", "1" } },
                                     { { "id", 15 },
                                       { "name", "Sonny Strosin" },
                                       { "rankingScore", 0.05 },
                                       { "distance", 118.55 },
                                       { "city", "Kuvalisside" },
                                       { "street", "Stark Lights" },
                                       { "house_number", "217" } },
                                     { { "id", 16 },
                                       { "name", "Claudie Mraz" },
                                       { "rankingScore", 0.75 },
                                       { "distance", 74.96 },
                                       { "city", "West Jenniffertown" },
                                       { "street", "Otis Club" },
                                       { "house_number", "5" } },
                                     { { "id", 17 },
                                       { "name", "Stacey King" },
                                       { "rankingScore", 0.29 },
                                       { "distance", 82.11 },
                                       { "city", "Donnellyburgh" },
                                       { "street", "Phil Village" },
                                       { "house_number", "19" } },
                                     { { "id", 18 },
                                       { "name", "Gabriel Veum" },
                                       { "rankingScore", 0.81 },
                                       { "distance", 108.35 },
                                       { "city", "Walkerfort" },
                                       { "street", "Stamm Mountain" },
                                       { "house_number", "241 a" } },
                                     { { "id", 19 },
                                       { "name", "Drucilla Lindgren" },
                                       { "rankingScore", 0.28 },
                                       { "distance", 21.17 },
                                       { "city", "West Dexter" },
                                       { "street", "Larkin Views" },
                                       { "house_number", "44" } },
                                     { { "id", 20 },
                                       { "name", "Jonas Hettinger" },
                                       { "rankingScore", 0.85 },
                                       { "distance", 69.68 },
                                       { "city", "North Doloresfort" },
                                       { "street", "Dean Road" },
                                       { "house_number", "10" } } });

        return x;
    });

    CROW_ROUTE(app, "/craftsmen")
    ([](const crow::request& req) {
        auto postalcode = req.url_params.get("postalcode");
        return "Hello World\n";
    });

    app.port(8080).multithreaded().run();
}
}
